// <auto-generated />
using LaundrySimulator2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaundrySimulator2.Migrations
{
    [DbContext(typeof(LaundrySimulatorReduxContext))]
    [Migration("20230804132604_AddDefaultMigration")]
    partial class AddDefaultMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaundrySimulator2.Classes.DefaultInventory", b =>
                {
                    b.Property<int>("InvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvId"));

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvId")
                        .HasName("PrimaryKey_InvId");

                    b.ToTable("DefaultInventory", (string)null);

                    b.HasData(
                        new
                        {
                            InvId = 1,
                            ItemDescription = "Run of the mill variety detergent.",
                            ItemName = "Laundry Detergent"
                        },
                        new
                        {
                            InvId = 2,
                            ItemDescription = "Your wallet. Tearing at the seams. Only a couple quarters.",
                            ItemName = "Wallet"
                        },
                        new
                        {
                            InvId = 3,
                            ItemDescription = "Something from your youth. How did they get here?",
                            ItemName = "JNCO Jeans"
                        },
                        new
                        {
                            InvId = 4,
                            ItemDescription = "Black t-shirt with Sailor Saturn on it since she's your favorite.",
                            ItemName = "Sailor Moon T-shirt"
                        },
                        new
                        {
                            InvId = 5,
                            ItemDescription = "Run of the mill variety detergent.",
                            ItemName = "Polo shirt with your name on it."
                        });
                });

            modelBuilder.Entity("LaundrySimulator2.Classes.PlayerName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerNames");
                });
#pragma warning restore 612, 618
        }
    }
}
